In [18]:
import random
import pandas as pd
from collections import defaultdict
import itertools

Moves:
first move only:
    double down - double the bet and take one more card
    split - seperate tow cards of the same calue into two hands
    surrender - forfeit the hand for half the bet back
    insurance - dealer face up card is ace but one-halg oringal bet that dealer has blackjack, pays 2 to 1
hit - take another cards
stand - take no more cards

Dealer 
hit until 17
hit soft 17 is a variation

In [ ]:
#exact combinatorial analysis is required
#actaully we do not want to run a random game for a basic stragery table 
#need to rewrite this to go over every possible hand and dealer hand conbination to generate an ev table

In [ ]:
def blackjack_basic_strategy_deterministic(number_of_decks = 1,
             sims = 10000,
             deck_pen = 0.3,
             dealer_hit_soft_17 = True,
             double_allowed = True,
             split_allowed = True,
             surrender_allowed = True,
             insurance_allowed = True,
             blackjack_payout = 1.5
             ):
    return

In [ ]:
def blackjack_basic_strategy_MC(
        number_of_decks = 6,
        sims = 2000000,
        deck_pen = 0.75,
        dealer_hit_soft_17 = True,
        double_allowed = True,
        split_allowed = False, #not included
        surrender_allowed = True,
        insurance_allowed = True,
        blackjack_payout = 1.5
):
    # Card Setup -------------------------------------------------
        bj_rank = ['A','2','3','4','5','6','7','8','9','10','10','10','10']
        single_deck = bj_rank * 4
        game_decks = single_deck * number_of_decks

        # All possible staring hands 
        bj_rank_unique = ['A','2','3','4','5','6','7','8','9','10']
        player_cards = []
        for i in bj_rank_unique:
                for j in bj_rank_unique:
                        if j < i:
                                continue
                        else:
                                player_cards.append(i,j)

        dealer_face = bj_rank_unique.copy()

    
    # Result Storage -------------------------------------------------
        results = defaultdict(lambda:{'winning': 0, 'stake': 0, 'count':0})

        def record(dealer_up, player_initial, move, profit, stake):
                key = (dealer_up, ','.join(sorted(player_initial)), move)
                results[key]['winning'] += profit + stake
                results[key]['stake'] += stake
                results[key]['stake'] += 1

    # Hand Value -------------------------------------------------
        def hand_values(card_list):
                output = 0
                aces = 0
                for i in card_list:
                        if i == 'A':
                                aces += 1
                                output += 11
                        else:
                                output += int(i)
                while output > 21 and aces > 0:
                        output -= 10
                        aces -= 1
                return output    
        
        def is_soft(hand):
                return 'A' in hand and hand_values(hand) <= 17

    # Dealer Move -------------------------------------------------

        def dealer_move(dealer_cards, deck_slice):
                cards = dealer_cards.copy()
                i = 0
                while True:
                        value = hand_values(cards)
                        if value > 21:
                                return cards, True # dealer bust
                        if value >= 17 and (value > 17 or not (dealer_hit_soft_17 and is_soft(cards))):  
                                return cards, False
                        if i >= len(deck_slice):
                                cards, value > 21
                        cards.append(deck_slice[i])
                        i += 1       
                return cards, hand_values(cards) > 21
        

 
    # Player Moves -------------------------------------------------
        def stand(player_cards, dealer_cards, deck_slice):
                dealer_fin, busted = dealer_move(dealer_cards, deck_slice)
                player_value = hand_values(player_cards)
                dealer_value = hand_values(dealer_fin)
                if player_value > 21: # not used here but useful in future for multi set moves
                        record(dealer_cards[0], player_cards[:2], 'stand', -1, 1)
                elif busted or player_value > dealer_value:
                        record(dealer_cards[0], player_cards[:2], 'stand', 1, 1)
                elif player_value == dealer_value: #push
                        record(dealer_cards[0], player_cards[:2], 'stand', 0, 1)
                else:
                        record(dealer_cards[0], player_cards[:2], 'stand', -1, 1)
                return 0
        
        def hit(player_cards, dealer_cards, deck_slice):
                cards = player_cards.copy()
                i = 0



                return
        

        
        def double(player_cards, dealer_cards, deck_slice):
                return
        def surrender(player_cards, dealer_cards, deck_slice):
                return
        def insurance(player_cards, dealer_cards, deck_slice):
                return

    # Sim -------------------------------------------------

    # Results Table -------------------------------------------------
        
        
        return

In [ ]:
def blackjack_basic_strategy_MC(number_of_decks = 1,
             sims = 10000,
             deck_pen = 0.3,
             dealer_hit_soft_17 = True,
             double_allowed = True,
             split_allowed = True,
             surrender_allowed = True,
             insurance_allowed = True,
             blackjack_payout = 1.5
             ):
    # card setup ------------------------------------------------
    card_values = {
        #'A' : [1, 11], note used
        '2' : [2],
        '3' : [3],
        '4' : [4],
        '5' : [5],
        '6' : [6],
        '7' : [7],
        '8' : [8],
        '9' : [9],
        '10' : [10],
        'J' : [10],
        'Q' : [10],
        'K' : [10]
    }
        
    # rank = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']
    # as suit not important and face cards just have a value of 10:
    bj_rank = ['A','2','3','4','5','6','7','8','9','10','10','10','10']
    single_deck = bj_rank * 4
    game_decks = single_deck * number_of_decks
    
    bj_rank_unique = ['A','2','3','4','5','6','7','8','9','10']
    player_cards = []
    for i in bj_rank_unique:
        for j in bj_rank_unique:
            if j < i:
                continue
            else:
                player_cards.append(i,j)

    dealer_face = bj_rank_unique.copy()

    # setting up results table ------------------------------------------------
    allowed_move = ['stand', 'hit']

    if double_allowed == True:
        allowed_move.append('double')
    if split_allowed == True:
        allowed_move.append('split')
    if surrender_allowed == True:
        allowed_move.append('surrender')
    if insurance_allowed == True:
        allowed_move.append('insurance')

    results = {}

    for dealer in dealer_face:
        for hand in player_cards:
            hand_key = ','.join(sorted(hand))
            for move in allowed_move:
                key = (dealer, hand_key, move)
                results[key] = {"winning": 0, "stake": 0}

    def update_results(player_cards, dealer_cards, move, stake):
        player_hand_value = hand_values(player_cards)
        dealer_hand_value = hand_values(dealer_cards)
        if dealer_hand_value > 21: # dealer bust
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["winning"] += stake * 2
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["stake"] += stake
        elif player_hand_value == dealer_hand_value: # push
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["winning"] += stake 
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["stake"] += stake
        elif player_hand_value > 21 or player_hand_value < dealer_hand_value: #player lost
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["stake"] += stake
        else: #player won
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["winning"] += stake * 2
            results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), move)]["stake"] += stake
    # ------------------------------------------------
    # Player Moves

    #### need to update so that a copy of the player and dealer hand as well as the current count is taken otherwise we override it

    def deal_cards(current_card):
        player_cards = [game_decks[current_card], game_decks[current_card + 2]]
        dealer_cards = [game_decks[current_card + 1], game_decks[current_card + 3]]
        current_card = current_card + 4
        return player_cards, dealer_cards, current_card
    
    def hit(pc_hit, dc_hit, cc_hit):

        pc_hit.append(game_decks[cc_hit])
        cc_hit += 1 
        if hand_values(pc_hit) < 22: #player not busted
            dc, cc_hit = dealer_move(dc_hit, cc_hit)
        update_results(pc_hit, dc_hit, 'hit', 1)
        return cc_hit
    
    def stand(pc_stand, dc_stand, cc_stand):
        dc_stand, cc_stand = dealer_move(dc_stand, cc_stand)
        update_results(pc_stand, dc_stand, 'stand', 1)
        return cc_stand
    
    def double(pc_double, dc_double, cc_double):
        pc_double.append(game_decks[cc_double])
        cc_double += 1 
        if hand_values(pc_double) < 22: #player not busted
            dc, cc = dealer_move(dc_double, cc_double)
        update_results(pc_double, dc_double, 'double', 2)
        return cc_double
    #will do later
    #def split():
    #    return
    #def surrender():
    #    return 
    #def insurance():
    #    return
    
    def play_legal_moves(player_cards, dealer_cards, current_card):
        # player Blackjack
        if hand_values(player_cards) == 21:
            #Dealer also has blackjack
            if hand_values(dealer_cards) == 21: 
                results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), 'stand')]["winning"] += 1  #push
                results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), 'stand')]["stake"] += 1
            else: 
                results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), 'stand')]["winning"] += 1 * (1 + blackjack_payout)
                results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), 'stand')]["stake"] += 1
            #dealer showing ace & blackjack
            if dealer_cards[0] == 'A' and hand_values(dealer_cards) == 21:
                results[(dealer_cards[0], ','.join(sorted(player_cards[:2])), 'stand')]["stake"] += 1
        else:
            pc_orig = player_cards.copy()
            dc_orig = dealer_cards.copy()
            cc_orig = current_card
            cc_out = current_card
            for i in allowed_move:
                if i == 'hit':
                    pc = pc_orig.copy()
                    dc = dc_orig.copy()
                    cc = cc_orig
                    print('hit')
                    print(pc)
                    print(dc)
                    print(cc)
                    cc_out = max(hit(pc, dc, cc), cc_out)

                if i == 'stand':
                    pc = pc_orig.copy()
                    dc = dc_orig.copy()
                    cc = cc_orig
                    print('stand')
                    print(pc)
                    print(dc)
                    print(cc)
                    cc_out = max(stand(pc, dc, cc), cc_out)

                if i == 'double':
                    pc = pc_orig.copy()
                    dc = dc_orig.copy()
                    cc = cc_orig
                    print('double')
                    print(pc)
                    print(dc)
                    print(cc)
                    cc_out = max(double(pc, dc, cc), cc_out)

        return cc_out
    
    # ------------------------------------------------
    # dealer move
    
    def dealer_move(dealer_cards, current_card):
        while True:
            value = hand_values(dealer_cards)
            soft = ('A' in dealer_cards) and value <= 17

            if value > 21:
                return dealer_cards, current_card
            if value > 17:  
                return dealer_cards, current_card
            if value == 17 and not dealer_hit_soft_17:
                return dealer_cards, current_card
            if value == 17 and dealer_hit_soft_17 and not soft:
                return dealer_cards, current_card

            # Hit
            dealer_cards.append(game_decks[current_card])
            current_card += 1 
        
    # ------------------------------------------------
    # hand value   
    def hand_values(card_list):
        output = 0
        aces = 0

        for i in card_list:
            if i == 'A':
                aces += 1
                output += 11
            else:
                output += card_values[i][0]

        while output > 21 and aces > 0:
            output -= 10
            aces -= 1
            
        return output    

    # ------------------------------------------------
    # simulation

    for i in range(sims):       
        current_card = 0
        
        random.shuffle(game_decks)
        while current_card < round(len(game_decks)*deck_pen):
            player_cards, dealer_cards, current_card = deal_cards(current_card)
            play_legal_moves(player_cards, dealer_cards, current_card)
    
    #creating an EV table
    results_df = pd.DataFrame(results).T
    results_df['ev'] = (results_df['winning']- results_df['stake']) / results_df['stake']

    return results_df

In [17]:
results = blackjack_basic_strategy_MC(number_of_decks = 1,
             sims = 1,
             deck_pen = 0.5,
             dealer_hit_soft_17 = True,
             double_allowed = True,
             split_allowed = False,
             surrender_allowed = False,
             insurance_allowed = False,
             blackjack_payout = 1.5
             )

stand
['3', '9']
['10', '10']
4
hit
['3', '9']
['10', '10']
4
double
['3', '9']
['10', '10']
4
stand
['6', '10']
['3', '6']
8
hit
['6', '10']
['3', '6']
8
double
['6', '10']
['3', '6']
8
stand
['3', '10']
['8', '10']
12
hit
['3', '10']
['8', '10']
12
double
['3', '10']
['8', '10']
12
stand
['5', '10']
['10', '8']
16
hit
['5', '10']
['10', '8']
16
double
['5', '10']
['10', '8']
16
stand
['4', '10']
['10', '10']
20
hit
['4', '10']
['10', '10']
20
double
['4', '10']
['10', '10']
20
stand
['5', '2']
['4', '9']
24
hit
['5', '2']
['4', '9']
24
double
['5', '2']
['4', '9']
24
stand
['9', '10']
['9', '5']
28
hit
['9', '10']
['9', '5']
28
double
['9', '10']
['9', '5']
28

In [9]:
results

                  winning     stake        ev
A  A,A   stand     1398.0    4002.0 -0.650675
         hit       2154.0    4002.0 -0.461769
         double    4308.0    8004.0 -0.461769
   2,A   stand     3016.0    8472.0 -0.644004
         hit       4630.0    8472.0 -0.453494
...                   ...       ...       ...
10 10,9  hit      34950.0  137067.0 -0.745015
         double   69900.0  274134.0 -0.745015
   10,10 stand   388962.0  271260.0  0.433908
         hit      39354.0  271260.0 -0.854921
         double   78708.0  542520.0 -0.854921

[1650 rows x 3 columns]

In [ ]:
#random.seed(1)

def game_sim(number_of_decks = 1,
             sims = 10000,
             deck_pen = 0.3,
             dealer_hit_soft_17 = True,
             double_allowed = True,
             split_allowed = True,
             surrender_allowed = True,
             insurance_allowed = True,
             blackjack_payout ='3:2'
             ):
    
    # ---------------------------------------------
    # setting up decks
    cards = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']

    card_values = {
        #'A' : [1, 11], note used
        '2' : [2],
        '3' : [3],
        '4' : [4],
        '5' : [5],
        '6' : [6],
        '7' : [7],
        '8' : [8],
        '9' : [9],
        '10' : [10],
        'J' : [10],
        'Q' : [10],
        'K' : [10]
    }

    single_deck = cards * 4

    decks = single_deck * number_of_decks

    dealer_face = cards.copy() 

    player_cards = []
    for i in range(len(single_deck)):
        for j in range(len(single_deck)):
            if j < i:
                continue
            else:
                player_cards.append([single_deck[i],single_deck[j]])
    # ------------------------------------------------
    #setting up results table 

    allowed_move = ['stand', 'hit']

    if double_allowed == True:
        allowed_move.append('double')
    if split_allowed == True:
        allowed_move.append('split')
    if surrender_allowed == True:
        allowed_move.append('surrender')
    if insurance_allowed == True:
        allowed_move.append('insurance')

    results = []
    for i in dealer_face:
        for j in player_cards:
            for k in allowed_move:
                results.append({
                    'dealer_face': i, 
                    'player_cards': ','.join(sorted(j)),
                    'move': k,
                    'wins': 0,
                    'losses': 0,
                    'total': 0
                    })

    results_df = pd.DataFrame(results)

    # ------------------------------------------------
    #moves    
    def deal_cards(current_card):
        player_cards = [decks[current_card], decks[current_card + 2]]
        dealer_cards = [decks[current_card + 1], decks[current_card + 3]]
        current_card = current_card + 4
        return player_cards, dealer_cards, current_card
    
    def next_move(first_move, current_card, card_list):
        if first_move == 'Y':
            #add in other moves here
            # change this to moves later 
            first_move = random.choice(allowed_move)
            if first_move == 'hit':
                return hit(current_card, card_list, first_move) 
            if first_move == 'double':
                return double()
            if first_move == 'split':
                return split()
            if first_move == 'surrender':
                return surrender()
            if first_move == 'insurance':
                return insurance()
            else: 
                return stand(card_list, current_card, first_move)
        if hand_values(card_list) == 21:
            return stand(card_list, current_card, first_move)
        else:
            move = random.choice(['hit', 'stand'])
            if move == 'hit':
                return hit(current_card, card_list, first_move)
            else: 
                return stand(card_list, current_card, first_move)
    
    def hit(current_card, card_list, first_move):
        card_list.append(decks[current_card])
        current_card += 1
        if hand_values(card_list) > 21:
            return 'Bust', current_card, first_move
        else:
            return next_move(first_move, current_card, card_list)
    
    def stand(card_list, current_card, first_move):
        return hand_values(card_list), current_card, first_move
    
    # to do 
    def double():
        return 
    def split():
        return
    def surrender():
        return 
    def insurance():
        return
    
    def dealer_move(dealer_cards, current_card):

        while True:
            value = hand_values(dealer_cards)
            soft = ('A' in dealer_cards) and value -11 + 1 <= 10 

            if value > 21:
                return 'Bust', current_card
            if value > 17:  
                return value, current_card
            if value == 17 and not dealer_hit_soft_17:
                return value, current_card
            if value == 17 and dealer_hit_soft_17 and not soft:
                return value, current_card

            # Hit
            dealer_cards.append(decks[current_card])
            current_card += 1
         
    # this needs to deal with aces
    def hand_values(card_list):
        output = 0
        aces = 0

        for i in card_list:
            if i == 'A':
                aces += 1
                output += 11
            else:
                output += card_values[i][0]

        while output > 21 and aces > 0:
            output -= 10
            aces -= 1
            
        return output
    
    # ------------------------------------------------
    #running simulation
    for i in range(sims):
        
        #burn card - shouldn't have any impact
        current_card = 1
        decks = single_deck * number_of_decks
        random.shuffle(decks)
        while current_card < round(len(decks)*deck_pen):
            first_move = 'Y'
            player_cards, dealer_cards, current_card = deal_cards(current_card)

            #blackjack
            if hand_values(player_cards) == 21:
                if hand_values(dealer_cards) == 21: 
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == 'stand'), 'total' ] += 1
                else:
                    if blackjack_payout == '3:2':
                        multiplier = 1.5
                    else:
                        multiplier = 1.2
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == 'stand'), 'wins' ] += 1 * multiplier
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == 'stand'), 'total' ] += 1
            
            #dealer showing ace & blackjack
            if dealer_cards[0] == 'A' and hand_values(dealer_cards) == 21:
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == 'stand'), 'losses' ] += 1
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == 'stand'), 'total' ] += 1

            
            player_result, current_card, first_move = next_move(first_move, current_card, player_cards.copy())                  

            if player_result == 'Bust':
                results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'losses' ] += 1
                results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'total' ] += 1
            else:
                dealer_result, current_card = dealer_move(dealer_cards.copy(), current_card)
                if dealer_result == 'Bust':
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'wins' ] += 1
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'total' ] += 1
                elif dealer_result > player_result:
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'losses' ] += 1
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'total' ] += 1
                else:
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'wins' ] += 1
                    results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == first_move), 'total' ] += 1

    return results_df

In [ ]:
re-write so only allows one move (additional hits just modeled on the rest of the table) and runs all possible move with the outcomes added to the table including EV 
combine all tens together 
new column in table for total

In [45]:
output =game_sim(number_of_decks = 2,
        sims = 100,
        deck_pen = 0.5,
        dealer_hit_soft_17 = True,
        double_allowed = False,
        split_allowed = False,
        surrender_allowed = False,
        insurance_allowed = False,
        blackjack_payout ='3:2')

C:\Users\Dominic\AppData\Local\Temp\ipykernel_22960\2484729990.py:192: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results_df.loc[(results_df['dealer_face'] == dealer_cards[0]) & (results_df['player_cards'] == ','.join(sorted(player_cards[:2]))) & (results_df['move'] == 'stand'), 'wins' ] += 1 * multiplier

In [36]:
output[output['total'] > 0]

     dealer_face player_cards   move  wins  losses  total
2              A          2,A  stand   0.0       1      1
4              A          3,A  stand   0.0       1      1
10             A          6,A  stand   0.0       1      1
13             A          7,A    hit   0.0       2      2
15             A          8,A    hit   0.0       1      1
...          ...          ...    ...   ...     ...    ...
2346           K        10,10  stand   1.0       0      1
2349           K         10,J    hit   0.0       1      1
2351           K         10,Q    hit   0.0       1      1
2353           K         10,K    hit   0.0       2      2
2363           K          K,Q    hit   0.0       2      2

[842 rows x 6 columns]